name: zShop
author: Maxlego08
main: fr.maxlego08.shop.ShopPlugin
website: https://groupez.dev
description: Shop plugin
version: 3.3.1
api-version: 1.13
folia-supported: true
depend:
  - zMenu
softdepend:
  - Vault
  - PlayerPoints
  - VotingPlugin
  - TokenManager
  - CoinsEngine
commands: