name: Auto Release

on:
  push:
    branches:
      - main  # Automatically run on push to main
  workflow_dispatch:  # Allow manual run from GitHub UI

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Extract plugin version from build.gradle.kts
        id: version
        run: |
          VERSION=$(grep -oP 'version\s*=\s*"\K[^"]+' build.gradle.kts | head -n1)
          echo "PLUGIN_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Build with Gradle
        run: ./gradlew iris

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v${{ env.PLUGIN_VERSION }}"
          git push origin "v${{ env.PLUGIN_VERSION }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PLUGIN_VERSION }}
          name: v${{ env.PLUGIN_VERSION }}
          files: build/Iris-${{ env.PLUGIN_VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
